### ISSUE TITLE
Crear clase Ticket

### ISSUE THREAD

**Issue by judithgispert** [AinohaBarcia/S3_03_DEVELOPERS_TEAM#17]

**Comment by AinohaBarcia** [comment]
He modificado la clase Ticket ya que estaba el ArrayList inicializado en atributos y se tiene que incializar dentro del constructor.

**Comment by AinohaBarcia** [comment]
Hola! acabo de actualizar el proyecto y me vuelve a salir la clase ticket con los errores de esta mañana.... mi no entender por que ... esta mañana se había modificado no??? mi pregunta es la siguiente: lo arreglo a nivel local o entendemos que me tengo que esperar a alguna actualización??? Gracias!!!
